"""create_onboarding_profiles

Revision ID: 19d1053e4ad7
Revises: 
Create Date: 2026-06-22 23:17:24.876579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d1053e4ad7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('objetivo', sa.String(length=32), nullable=False),
    sa.Column('tipo_prova', sa.String(length=128), nullable=False),
    sa.Column('data_prova', sa.Date(), nullable=True),
    sa.Column('horas_por_dia', sa.Float(), nullable=False),
    sa.Column('materias_dificuldade', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_profiles_id'), 'onboarding_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_profiles_session_id'), 'onboarding_profiles', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_profiles_session_id'), table_name='onboarding_profiles')
    op.drop_index(op.f('ix_onboarding_profiles_id'), table_name='onboarding_profiles')
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###
